[tool.poetry]
name = "wallpaper-dev"
version = "0.9.0"
description = ""
authors = ["vanton"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.10"
colorama = "^0.4.6"
pillow = "^11.0.0"
rich = "^13.9.4"

[build-system]
requires = ['poetry-core~=1.0']
build-backend = 'poetry.core.masonry.api'
