[tool.poetry]
package-mode = false
authors = ["vanton"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
repository = "https://github.com/vanton/wallpaper"
homepage = "https://github.com/vanton/wallpaper"
keywords = ["wallhaven", "python", "wallpaper"]

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "^24.1.0"
aiohttp = "^3.11.8"
asyncio = "^3.4.3"
logging = "^0.4.9.6"
requests = "^2.32.3"
rich = "^13.9.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ['poetry-core>=1.0']
build-backend = 'poetry.core.masonry.api'
