[tool.poetry]
name = "wallpaper"
version = "0.10.2"
description = ""
authors = ["vanton"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.9.4"
logging = "^0.4.9.6"
requests = "^2.32.3"
aiohttp = "^3.11.7"
aiofiles = "^24.1.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ['poetry-core>=1.0']
build-backend = 'poetry.core.masonry.api'
